version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "le-lapin-order"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g3l3bfbxaeah"
s3_prefix = "le-lapin-order"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
